/**
 * Source of the plugin SkillCat installs into OpenCode's global plugin
 * directory. It is self-contained (no SkillCat imports) and only ever appends
 * small JSON lines to the spool file, so a failure can never break the agent.
 *
 * The spool path is baked in at install time; phrase length is capped
 * generously here and truncated further on ingest per user settings, so
 * changing the retention options never requires reinstalling.
 */
export const OPENCODE_MARKER = 'skillcat-bridge:opencode:v1';

export function buildOpencodePluginSource(spoolPath: string): string {
  const spool = JSON.stringify(spoolPath);
  return `// ${OPENCODE_MARKER}
// Auto-generated by SkillCat. Do not edit; remove it from SkillCat settings.
import { appendFile } from "node:fs/promises"

const SPOOL = ${spool}
const HARD_CAP = 4000

function textOf(entry) {
  const parts = Array.isArray(entry && entry.parts) ? entry.parts : []
  const chunks = []
  for (const part of parts) {
    if (part && part.type === "text" && typeof part.text === "string" && !part.synthetic) {
      chunks.push(part.text)
    }
  }
  return chunks.join("\\n").trim()
}

function unwrap(res) {
  return res && typeof res === "object" && "data" in res ? res.data : res
}

async function lastUserText(client, sessionId) {
  try {
    if (!client || !client.session || !client.session.messages) return null
    const data = unwrap(await client.session.messages({ path: { id: sessionId } }))
    if (!Array.isArray(data)) return null
    for (let i = data.length - 1; i >= 0; i -= 1) {
      const entry = data[i]
      if (entry && entry.info && entry.info.role === "user") {
        const text = textOf(entry)
        if (text) return text
      }
    }
  } catch {}
  return null
}

async function resolveTask(client, sessionId) {
  try {
    if (client && client.session && client.session.todo) {
      const todos = unwrap(await client.session.todo({ path: { id: sessionId } }))
      if (Array.isArray(todos)) {
        const active = todos.find((item) => item && item.status === "in_progress")
        if (active) {
          return {
            task: typeof active.content === "string" ? active.content : active.title || null,
            taskId: active.id || null,
          }
        }
      }
    }
  } catch {}
  try {
    if (client && client.session && client.session.get) {
      const info = unwrap(await client.session.get({ path: { id: sessionId } }))
      if (info && typeof info.title === "string" && info.title) {
        return { task: info.title, taskId: null }
      }
    }
  } catch {}
  return { task: null, taskId: null }
}

export const SkillCatBridge = async ({ client, directory }) => {
  return {
    "tool.execute.after": async (input, output) => {
      try {
        if (!input || input.tool !== "skill") return
        const args = (output && output.args) || input.args || {}
        const name = args.name
        if (typeof name !== "string" || !name) return
        const sessionId = input.sessionID || input.sessionId || null

        let phrase = null
        let task = null
        let taskId = null
        if (sessionId) {
          phrase = await lastUserText(client, sessionId)
          const resolved = await resolveTask(client, sessionId)
          task = resolved.task
          taskId = resolved.taskId
          if (!task && phrase) task = phrase.slice(0, 80)
        }
        if (phrase && phrase.length > HARD_CAP) phrase = phrase.slice(0, HARD_CAP)

        await appendFile(
          SPOOL,
          JSON.stringify({
            v: 1,
            adapterId: "opencode",
            kind: "tool",
            name,
            source: "model",
            phrase,
            task,
            taskId,
            sessionId,
            cwd: directory || null,
            ts: Date.now(),
          }) + "\\n",
        )
      } catch {
        // A bridge failure must never break the agent.
      }
    },
  }
}
`;
}
