#!/usr/bin/env bash
#
# Dependency security scan for CI.
#
# Runs `pnpm audit` and, when high/critical advisories are found, attempts to
# fix them: first by updating the vulnerable packages in the lockfile, then by
# adding pnpm overrides if anything remains. A Markdown summary is written to
# `audit-report.md` so the workflow can use it as the pull-request body.
#
# Always exits 0 (unless the script itself is broken) so the workflow can still
# run the test suite and open a PR with whatever fixes were applied.
set -uo pipefail

REPORT="${AUDIT_REPORT:-audit-report.md}"
LEVEL="${AUDIT_LEVEL:-high}"
GITHUB_OUTPUT="${GITHUB_OUTPUT:-/dev/null}"

log() { printf '%s\n' "$*"; }

WORKSPACE_MANIFEST="pnpm-workspace.yaml"
WORKSPACE_SNAPSHOT="$(mktemp)"
cp "$WORKSPACE_MANIFEST" "$WORKSPACE_SNAPSHOT"
trap 'rm -f "$WORKSPACE_SNAPSHOT"' EXIT

# Restore the manifest snapshot so a rollback does not leave generated
# overrides behind.
restore_workspace_manifest() { cp "$WORKSPACE_SNAPSHOT" "$WORKSPACE_MANIFEST"; }

: > "$REPORT"
{
  echo "## Dependency audit"
  echo
} >> "$REPORT"

log "Running pnpm audit (audit level: $LEVEL)…"
audit_out="$(pnpm audit --audit-level="$LEVEL" --ignore-registry-errors 2>&1)"
audit_status=$?

if [ "$audit_status" -eq 0 ]; then
  log "No high/critical advisories found."
  echo "No high/critical advisories were found. ✅" >> "$REPORT"
  echo "vulnerable=false" >> "$GITHUB_OUTPUT"
  echo "remaining=false" >> "$GITHUB_OUTPUT"
  exit 0
fi

log "High/critical advisories found."
{
  echo "pnpm audit reported high/critical advisories:"
  echo
  echo '```'
  echo "$audit_out"
  echo '```'
  echo
} >> "$REPORT"
echo "vulnerable=true" >> "$GITHUB_OUTPUT"

log "Attempting fix with 'pnpm audit --fix update'…"
pnpm audit --fix update >/dev/null 2>&1 || true
pnpm install --no-frozen-lockfile >/dev/null 2>&1 || true

if ! pnpm audit --audit-level="$LEVEL" --ignore-registry-errors >/dev/null 2>&1; then
  log "Still vulnerable after the lockfile update; attempting 'pnpm audit --fix override'…"
  # `pnpm audit --fix override` rewrites pnpm-workspace.yaml and can emit an
  # override for a version that was never published. That makes the follow-up
  # install fail and leaves the lockfile out of sync with the manifest, which
  # is what produces ERR_PNPM_LOCKFILE_CONFIG_MISMATCH on later `pnpm run`
  # commands (e.g. the typecheck step). If the generated overrides cannot be
  # installed, roll them back so the lockfile stays consistent.
  pnpm audit --fix override >/dev/null 2>&1 || true
  if ! pnpm install --no-frozen-lockfile >/dev/null 2>&1; then
    log "The overrides generated by 'pnpm audit --fix override' cannot be installed; rolling them back."
    restore_workspace_manifest
    pnpm install --no-frozen-lockfile >/dev/null 2>&1 || true
  fi
fi

remaining_out="$(pnpm audit --audit-level="$LEVEL" --ignore-registry-errors 2>&1)"
if [ $? -eq 0 ]; then
  log "All high/critical advisories resolved."
  echo "All high/critical advisories were resolved by the automated fix. ✅" >> "$REPORT"
  echo "remaining=false" >> "$GITHUB_OUTPUT"
else
  log "Some high/critical advisories remain."
  {
    echo "Some high/critical advisories remain after the automated fix and need a manual look:"
    echo
    echo '```'
    echo "$remaining_out"
    echo '```'
  } >> "$REPORT"
  echo "remaining=true" >> "$GITHUB_OUTPUT"
fi

exit 0
